"""empty message

Revision ID: f8e896d5cda0
Revises: 
Create Date: 2023-03-05 11:25:35.881198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8e896d5cda0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    user_roles = op.create_table('user_roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=False),
    sa.Column('hierarchy_level', sa.Integer(), nullable=False),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hierarchy_level')
    )
    op.bulk_insert(
        user_roles,
        [
            {"id": 1, "role_name": "Super Admin", "hierarchy_level": 0, "is_delete": False, "is_active" : True},
            {"id": 2, "role_name": "Admin", "hierarchy_level": 1, "is_delete": False, "is_active" : True},
            {"id": 3, "role_name": "Staff", "hierarchy_level": 2, "is_delete": False, "is_active" : True},
            {"id": 4, "role_name": "Editor", "hierarchy_level": 3, "is_delete": False, "is_active" : True},
            {"id": 5, "role_name": "Student", "hierarchy_level": 4, "is_delete": False, "is_active" : True},

        ],
    ),
    op.create_table('users_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.Column('public_id', sa.String(length=100), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('user_role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_role_id'], ['user_roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('nationality', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('user_address', sa.Text(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('reporting_to_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['users_table.id'], ),
    sa.ForeignKeyConstraint(['reporting_to_id'], ['users_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profiles')
    op.drop_table('users_table')
    op.drop_table('user_roles')
    # ### end Alembic commands ###
